### PR TITLE
Agent Field View Customization

### PR DESCRIPTION
**Pull request by abdel**
We required more flexibility re: the agent field view size without manually modifying constants. Instead of using constants for the field size, this pull request simply moves it to a class member that can be easily overridden using a wrapper. I have also included a wrapper, `AgentViewWrapper` that takes in `agent_view_size` as a parameter.

On a side note, this change also introduced ideas for further field view customisation. In a separate branch, I have also made some changes to place the agent in the centre of the field view. I'm wondering if that would be a good fit as a follow-up pull request as well, or if it contradicts some underlying philosophy.

### CODE REVIEW

**Comment by maximecb** [comment]
Hi @abdel, you are not the first one to need this feature, so I think it's a nice initiative to make this change. The one comment I have is that I think it might nicer to pass this as an argument to the MiniGridEnv class instead of relying on a wrapper, or at least to allow doing that. Though I guess the reason you went with this approach is that it still works with the `gym.make()` interface?

As a sidenote, if you think that using a wrapper is better, you should ideally set `env.unwrapped.observation_space` and not directly `env.observation_space` because I don't think that will work when using multiple wrappers. A last point would be, you don't seem to be using the `env.obs_array_size` variable, so maybe we could get rid of that?

**Comment by abdel** [comment]
Hi @maximecb - yeah, ideally I wanted it to still work with `gym.make()` and all existing environments, so that's why I thought the wrapper approach was better, avoiding the need to create custom envs. 
Although if it's an argument to `MiniGridEnv`, that then creates a class member, it would still be overridable anyway, since the other environments will extend it?

I only used `ImgObsWrapper` & `FullyObsWrapper` in my tests, but I'll make the suggested changes to avoid any potential issues with other wrappers.

**Comment by maximecb** [comment]
> if it's an argument to MiniGridEnv, that then creates a class member, it would still be overridable anyway, since the other environments will extend it?

We can have both this and a wrapper 👍

**Comment by abdel** [comment]
@maximecb Hmm, it seems like I have to set `self.observation_space`, not `env.observation_space` or `env.unwrapped.observation_space`. If I don't set the `self.observation_space`, then this is the behaviour:

```
# with env.unwrapped.observation_space or env.observation_space
env = gym.make(..) # env.observation_space == (7, 7, 3)
env = AgentViewWrapper(env, agent_view_size=3) # env.observation_space == (7, 7, 3)
env = ImgObsWrapper(env) # env.observation_space == (7, 7, 3)

# with self.observation_space (expected)
env = gym.make(..) # env.observation_space == (7, 7, 3)
env = AgentViewWrapper(env, agent_view_size=3) # env.observation_space == (3, 3, 3)
env = ImgObsWrapper(env) # env.observation_space == (3, 3, 3)
```

**Comment by maximecb** [comment]
Looks good, well done @abdel !

**Pull request merged**
