### PR TITLE
Implement Lava tiles and LavaCrossing environment (#7)

### PR DESCRIPTION
**Pull request by abaisero**
* Add color orange

 * Add new tile type Lava

 * Add new environment LavaCrossing

 * Add new drawPolyline method to Renderer

### CODE REVIEW

**Comment by maximecb** [comment]
Hi there! Very glad to see you took up this feature :)

Overall, looks very good! :+1:

A few comments & requests:

- I would rather not add new colors because it might break existing code. Sounds silly, but it's true. We could just say the lava is red (though you could still draw it orange-red in the UI)

- `LavaCrossingEnv9x9N2` => Should be `LavaCrossingS9N2Env` by convention

- Would you mind posting a screenshot of the result?

- Would also be great if you could add the level description to the README, along with a screenshot

**Comment by abaisero** [comment]
Hey;  I really like the gist of these environments, and thought I'd give a quick shot at this simple issue to get a feel of the inner workings.  I hope I got the naming convention right, in the sense that I should use it for both environment class and environment string id?  I tried to keep the coding style consistent with the rest of the repo.

Here are some screenshots, one from each registered environment:

image

image

image

image

Let me know if you have further questions!

**Comment by maximecb** [comment]
Looks good!

I found another minor issue. You shouldn't directly use `np.random.choice` and such. There's an internal RNG `self.np_random`. You should always use this for any pseudorandom generation. That way, we can guarantee that if someone sets `env.seed(some_integer)`, they will always get the same environment for the same seed. Apart from that, ready to merge :)

**Comment by abaisero** [comment]
Ooops, I hoped wrong.. I don't know how those two slipped my search!  Thanks for fixing.

**Comment by maximecb** [comment]
No problem. Thanks very much for implementing this.

**Pull request merged**
