### PR TITLE
Classical env and wrappers (#6, #13, #22)

### PR DESCRIPTION
**Pull request by d3sm0**
* Add Classical-v0 4 rooms env

* Add image wrapper

* Add full state wrapper

### CODE REVIEW

**Comment by maximecb** [comment]
The code looks good overall,  here is my feedback:
- I would name the env just FourRooms-v0, because the name "four rooms" is already somewhat known in RL
- I don't understand why you redefined `place_obj` and `place_agent`. I would maybe just put the goal and agent at the positions passed as input if these are not None, and otherwise let the base class `place_obj` and `place_agent` choose the positions (they should be returned from the functions)
- `ImgObsWrapper`, looks good, but you should also define the `observation_space` field correctly, to be an image instead of a dictionary
- `FullyObsWrapper`, pretty good, with the caveat that the agent isn't going to be visible in the grid encoding. I think you could probably just use a hack, like setting the values to (255, 255, 255) where the agent is, or something. Though you also need to encode its direction, so maybe (255, direction, 0), see the `agent_dir` and `agent_pos` fields of MiniGridEnv.

**Comment by d3sm0** [comment]
Thanks for the feedback! Got all done except the grid encoding. Sorry, if I ask but why do you want the agent placed in the grid encoding if the grid encoding is used only in the __str__ method of the env and there is no ANSI rendering?

**Comment by maximecb** [comment]
It's the observation that is fed to a neural network. If it's a full observation, it needs to have the agent in it, because otherwise, the network can't know where the agent is, and so will not be able to learn a good policy.

**Comment by d3sm0** [comment]
Sorry but, I added a test for the `FullyObsWrapper`, and looking at the image you can see the all world with the agent in it, which is what the neural network will get as the input.

**Comment by maximecb** [comment]
Looks ready to merge, apart from the changes to `gym_minigrid/minigrid.py` which I would like to reverse.

**Comment by d3sm0** [comment]
Should be all good. I copied from the master. Sorry i'm still a n00b  '-_-

**Comment by maximecb** [comment]
No problem. Thank you for contributing to this project, and for being patient :)

**Comment by d3sm0** [comment]
Oh it was super easy, you wrote great code 👍

**Pull request merged**
