### PR TITLE
Format ids to satisfy gym.make's requirements

### PR DESCRIPTION
**Pull request by edran**
This PR allows users to simply do `gym.make(env_id)`.

Previously, all envs had breaking ids, which I normalised to follow the regex in gym.register: https://github.com/openai/gym/blob/812c46cbadfffedd5ee024379ff9d7a5673ff474/gym/envs/registration.py#L9

I've also centralised all registration into `envs.__init__`, since that is also the recommended way (and it makes it easier to manage them).

### CODE REVIEW

**Comment by edran** [comment]
Note: I manually tested only a few envs after the changes.

**Comment by edran** [comment]
Tests pass now, locally. I've amended the last commit, so you need to re-run CI.

**Comment by maximecb** [comment]
Hm, are dashes now allowed in OpenAI Gym env ids? This has worked fine until now. I'd rather not break code by changing all the env ids unless necessary.

**Comment by edran** [comment]
Hmm oddly I can't seem to reproduce the errors I was getting. It appears dashes might be allowed in group-1, so gonna close this PR for now :)

**Pull request closed without merging**
